[build]
  publish = "build"
  command = "cp env.netlify .env && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://axomclash.onrender.com"
  REACT_APP_SOCKET_URL = "https://axomclash.onrender.com"
  REACT_APP_APP_NAME = "CampusClash"
  REACT_APP_APP_VERSION = "1.0.0"
  REACT_APP_ENABLE_CHAT = "true"
  REACT_APP_ENABLE_GAMES = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
